= Guide de rendu de documents en 1°année BTS SN
:author: Gilles Blengino, Thierry Vaira
:email: tvaira@free.fr
:revnumber: v0.2
:revdate: 23/08/2021
:revremark: 
:sectnums:
:toc: left
:toclevels: 4
:toc-title: Sommaire
:description: Guide de rendu de Travaux Pratiques en 1°année BTS SN
:keywords: 
:imagesdir: ./images/
:sourcedir: ./src/
:source-highlighter: highlightjs
:highlightjs-theme: rainbow
:stem:

////
:highlightjs-theme: xcode
:highlightjs-theme: androidstudio
:highlightjs-theme: googlecode
:highlightjs-theme: github
:highlightjs-theme: foundation
:highlightjs-theme: idea
:highlightjs-theme: rainbow
:highlightjs-theme: vs
:highlightjs-theme: sunburst
:highlightjs-theme: tomorrow
:highlightjs-theme: railscasts
:highlightjs-theme: zenburn
////

ifdef::backend-html5[]
++++
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++
:html:
endif::[]

:icons: font

:home: https://btssn-lasalle84.github.io/guides-developpement-logiciel/

ifdef::backend-pdf[]
{author} - <{email}> - version {revnumber} - {revdate} - {home}[btssn-lasalle84.github.io]
endif::[]

== Convention de nommage

Une convention de nommage permet, entre autres, d'identifier, classer naturellement les documents. La nomenclature doit être adaptée au contexte.

Dans un environnement scolaire, les caractéristiques suivantes doivent être facilement identifiables :

- La classe (pour les courriels)
- Les nom et prénom de l'élève
- Le type de devoir (DM, TP, TD, etc.)
- Le titre du sujet

[IMPORTANT]
====
Tous documents rendus sans respect de la convention de nommage ne seront pas pris en compte pour la notation et seront considérés comme travail non rendu et donneront la note de 0.
====

== Rendu des documents sur le serveur

=== Rendu d'un document unique

Comme les rendus se trouvent tous dans un même dossier (localisation fournie par le professeur). Les documents doivent :

- Être fournis au format demandé ET/OU dans un format universel	(PDF pour un document non modifiable par exemple).
- Le nom de fichier doit être composé du Nom, Prénom, Type de devoir et son titre.
- Il existe des règles particulières selon le travail demandé (TP, TD, DM, etc.). Vérifier les consignes données.

*Exemple :* `NOM Prenom - Rendu DM algo Tableau.pdf`

- NOM en majuscule, non accentué
- Prénom, Casse _pascal case_, non accentué
- Type de devoir, ici un rendu de devoir maison (abréviation *DM*).
- Le titre du document ici pour le sujet d'algorithmie, un exercice sur les tableaux.
- Au format demandé (et donc avec l'extension correspondante) ou universel.

=== Rendu de documents multiples

Certains rendus, comme les TPs, possèdent plusieurs fichiers (par exemple, un rendu par exercice pour les travaux pratiques), une arborescence est nécessaire dans le dossier de rendu (localisation fournie par le professeur).

Exemple pour les rendus correspondant au TP algorithmie, les tableaux, le dossier « Algo Tableau » a été fourni :

----
Algo Tableau
	 NOM Prénom
		 Nom exercice 1
			 Sources (*.h ; *.c ; *.cpp ; *.sql ; etc.)
			 NOM Prénom - Rapport – Nom exercice 1.pdf
		 Nom exercice 2
			 Sources (*.h ; *.c ; *.cpp ; *.sql ; etc.)
			 NOM Prénom - Rapport – Nom exercice 3.pdf
		 Nom exercice 3
			 Sources (*.h ; *.c ; *.cpp ; *.sql ; etc.)
			 NOM Prénom - Rapport – Nom exercice 3.pdf
----

== Devoir maison (par courriel)

=== Date de réception

Vous devez faire parvenir un document à une personne.

[TIP]
====
En entreprise, si vous envoyez votre rapport à votre responsable la veille de la présentation, il n'aura certainement pas assez de temps pour vérifier les chiffres ou discuter du contenu avec vous. Plus un sujet est important et/ou volumineux, plus il doit être fourni tôt.
====

Pour les devoirs “maison”, la date butoir est toujours fixée.

Il existe trois cas concernant la réception d'un devoir maison correctement fait. Il peut être envoyé :

- rapidement (ASAP ; avant j-2)
- dans les délais (j-2, j-1)
- en retard (j, j+x)

ASAP:: Un sigle qui signifie _As Soon As Possible_. C'est une expression militaire américaine issue du vocabulaire radio professionnel et passée dans le *jargon informatique* qui signifie « Dès Que Possible » / « le plus rapidement possible ». En français, l'abréviation correspondante est DQP.

Vous remarquerez que l'envoi le jour même est déjà considéré comme un retard. Il faut donc s'assurer que le destinataire le reçoive la veille (heure de réception jusqu'à 23h59).

[TIP]
====
*Le saviez-vous ?*

Les fournisseurs de courriers électroniques s'engagent à transmettre vos courriels en moins de 72 heures. 
Ce qui signifie qu'un courriel peut arriver 3 jours après son envoi.
====

=== Expéditeur

L'adresse d'expéditeur ne doit pas être folklorique et doit contenir le nom et prénom (en intégralité, sans abréviation).

En cas d'homonyme lors de la création de la boite email, on peut y ajouter son département, ou la notation "pro".

On vérifie également que le compte de messagerie est correctement renseigné avec son nom et prénom.

On peut classer les adresses de courriel en trois catégories :

- Les adresses folkloriques
- Les adresses correctes mais dont le profil (nom, prénom du compte) est mal renseigné ou incomplet.
- Les adresses professionnelles

=== Objet

L'objet d'un courriel est obligatoire.

Il permet au destinataire de savoir immédiatement ce que le courriel va contenir. Il peut servir également au classement automatique pour certains logiciels.

Cet objet peut-être :

* Folklorique, non renseigné.
* Ne pas contenir toutes les informations nécessaires.
* Professionnel et il contient :
    ** La classe, le NOM, Prénom de l'expéditeur car ça reste un document à faire parvenir à un professeur.
    ** L'objet, c'est ce que je fais parvenir (un rendu de DM, rendu d'exercice, etc.)
    ** Le titre de l'objet Rapport de stage, Rendu DM – Nom du DM, etc.

*Exemple :* `1TS NOM Prénom - Rendu DM - Algo Tableau`

=== Corps

Si l'objet peut être le titre, le corps peut être comparé à un résumé. Il doit également être professionnel.

*Exemple :*

----
Bonjour Monsieur,

Comme demandé vous trouverez ci-joint l'archive contenant mon devoir maison sur l'algorithme de tableau.

Vous en souhaitant bonne réception.

Cordialement

G. BLENGINO
----

=== Pièces jointes

La pièce jointe est la partie la plus importante de votre envoi.

Il vous faut cependant :

- Vérifier en premier lieu si on ne vous a pas demandé un fichier particulier (archive, présentation, etc.).
- S'assurer avant de créer l'archive que vous avez bien respecté l'arborescence et la convention de nommage pour les documents.
- S'assurer de fournir le format qui a été demandé.
- N'envoyer pas de multiple fichier (sauf si c'est demandé).
- N'envoyer pas votre travail dans le corps du message (sauf si c'est demandé).
- En cas d'envoi de documents multiples, il est nécessaire de regrouper les fichiers dans une archive. L'archive doit :
    ** Être de type universelle (`zip` pour une archive).
    ** Le nom de l'archive doit contenir : Le NOM et Prénom de l'auteur, le type de devoir et son nom.

*Exemple :* `NOM Prénom - DM Algo Tableau.zip`

***

ifdef::backend-html5[]
Site : {home}[btssn-lasalle84.github.io]
endif::[]

ifdef::backend-pdf[]
{author} - <{email}> - version {revnumber} - {revdate} - {home}[btssn-lasalle84.github.io]
endif::[]
